name: Hyper Branch pipeline

on:
  push:
    branches: [hyper_branch]
  pull_request:
    branches: [hyper_branch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Hyper-parameter regression
        run: |
          python hyper.py
