name: Regression branch Pipeline

on:
  push:
    branches: [reg_branch]
  pull_request:
    branches: [reg_branch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          # python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Regression
        run: |
          python regression.py
